// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SodicTask.Models;

namespace SodicTask.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20210228023634_frst")]
    partial class frst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SodicTask.Models.Category", b =>
                {
                    b.Property<int>("CatagNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IsAvailable")
                        .HasColumnType("smallint");

                    b.Property<short>("LevelNo")
                        .HasColumnType("smallint");

                    b.Property<int>("ParentNo")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatagNo");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SodicTask.Models.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatagNo")
                        .HasColumnType("int");

                    b.Property<string>("ProdDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdMainImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubCatag")
                        .HasColumnType("int");

                    b.Property<int?>("categoryCatagNo")
                        .HasColumnType("int");

                    b.HasKey("ProdId");

                    b.HasIndex("categoryCatagNo");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SodicTask.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<string>("ProdImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductProdId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductProdId");

                    b.ToTable("ProductImags");
                });

            modelBuilder.Entity("SodicTask.Models.Product", b =>
                {
                    b.HasOne("SodicTask.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("categoryCatagNo");

                    b.Navigation("category");
                });

            modelBuilder.Entity("SodicTask.Models.ProductImage", b =>
                {
                    b.HasOne("SodicTask.Models.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductProdId");
                });

            modelBuilder.Entity("SodicTask.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SodicTask.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
